
spring:
  datasource:
#    url: jdbc:mysql://18.236.117.247:3306/LOYALTY_APP?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/LOYALTY_APP?createDatabaseIfNotExist=true
    username: root
    password: password
    hikari:
      initialization-fail-timeout: 0
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8090

keycloak:
  realm: master
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8180}/auth
  resource: spring-app
  bearer-only: true