
spring:
  datasource:
    #url: jdbc:mysql://mydatabase.cxbkosas0ihq.us-west-2.rds.amazonaws.com:3306/LOYALTY_APP?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/LOYALTY_APP?createDatabaseIfNotExist=true
    username: root
    password: password
    #username: renu
    #password: renukeswar
    hikari:
      initialization-fail-timeout: 0
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

server:
  port: 8091


jwt:
  secret: javainuse
  expirationDateInMs: 1000000
  refreshExpirationDateInMs: 900000