
spring:
  datasource:
    url: jdbc:mysql://localhost:6666/LOYALTY_APP?createDatabaseIfNotExist=true
    username: root
    password: admin123
    hikari:
      initialization-fail-timeout: 0
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8090

